apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx-app  # Ensure this namespace exists
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # Choose a port within 30000-32767
